name: Generate and Publish Artefacts

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OUT_PATH: "output"
      DATE_TMP: $(date +\%Y\%m\%d)

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install gpsbabel
        python -m pip install --upgrade pip
        pip install -U pylint
        pip install -U aerofiles
        echo "DATE=$(date +\%Y\%m\%d)" >> $GITHUB_ENV

    - name: "Create the release artefacts"
      run: |
        ./release.bash ${OUT_PATH}
        ls -larth ${OUT_PATH}
        ls -larth ${{ env.OUT_PATH }}
        echo "111 todo ${DATE}"
        echo "222 todo ${{ env.DATE_TMP }}"

    - name: "Update Gist: CSV"
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 86d782cc0405dd54a80eecc3838ffe83
        gist_file_name: ZA_Cape_UNRELEASED.cup.csv
        file_path: ./${{ env.OUT_PATH }}/ZA_Cape_${{ env.DATE_TMP }}.cup.csv

    - name: "Update Gist: GeoJSON"
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 736c3658c29ba2a29abffdc2917e1839
        gist_file_name: ZA_Cape_UNRELEASED.geojson
        file_path: ./${{ env.OUT_PATH }}/ZA_Cape_${{ env.DATE_TMP }}.geojson

    - uses: actions/upload-artifact@v2
      with:
        name: "Create a releasable SeeYou CUP file"
        path: ./${{ env.OUT_PATH }}/ZA_Cape_${{ env.DATE_TMP }}.cup
        if-no-files-found: error  # 'warn' or 'ignore' are also available, defaults to `warn`

