name: Generate artefacts

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OUT_DIR: "output"

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install gpsbabel
        python -m pip install --upgrade pip
        pip install -U pylint
        pip install -U aerofiles

    - name: Create release artefacts
      run: |
        ./release.bash ${OUT_DIR}
        ls -larth ${OUT_DIR}

    - uses: actions/upload-artifact@v2
      with:
        name: artefacts
        path: output/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Update CSV Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 06794ffd3ed70fa8b9dbab5b65635106
        gist_file_name: ZA_Cape_20211006.cup.csv
        file_path: ./output/ZA_Cape_20211006.cup.csv

    - name: Update GeoJSON Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 4925e546693db0c25d874880a32533c3
        gist_file_name: ZA_Cape_20211006.geojson
        file_path: ./output/ZA_Cape_20211006.geojson
